### ISSUE TITLE
Small fix in example for tenantConfig.template.json

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-services.github.io#20]
With `"themesConfig": "./themesConfig.json",` within the template [1] I am getting the error
```
Exception: Failed to read themes configuration /srv/qwc_service/config-in/<tenant>/.././themesConfig.json
```
This should be omitted in the template, as it is specified within the `tenantConfig.json` of each tenant [2].

[1] https://github.com/qwc-services/qwc-services.github.io/blob/master/src/topics/MultiTenancy.md?plain=1#L189
[2] https://github.com/qwc-services/qwc-services.github.io/blob/master/src/topics/MultiTenancy.md?plain=1#L170

**Comment by manisandro** [comment]
There is since also the possibility to specify a base themesConfig.json which is then inherited/merged with the themesConfig.json of the tenants [1]. So in a template, `./themesConfig.json` now refers to a path relative to the `tenantConfig.template.json`. I need to clarify this in the documentation.

[1] https://github.com/qwc-services/qwc-config-generator/pull/68

**Comment by danceb** [comment]
Ah I see, thanks for clarification!

**Comment by manisandro** [comment]
I've added a remark in https://github.com/qwc-services/qwc-services.github.io/commit/88fc583ee255ff10bd59364d1e193a40e17c8ff1
